upstream spring_cluster {
    least_conn;
    server 127.0.0.1:8080;
    server 127.0.0.1:8081;
    server 127.0.0.1:8082;
    keepalive 32;
}

stream {
    upstream mqtt_broker {
        server 127.0.0.1:1883;
    }
    server {
        listen 1883;
        proxy_pass mqtt_broker;
    }
}

http {
    server {
        listen 80;
        location / {
            proxy_pass http://spring_cluster;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}