
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

quarkus.http.port=8082
quarkus.grpc.server.port=9001
quarkus.grpc.server.use-separate-server=false

# Configuramos el cliente gRPC que llamaremos "cliente-topologia"
quarkus.grpc.clients.cliente-topologia.host=localhost
quarkus.grpc.clients.cliente-topologia.port=8081

# Desactivamos TLS temporalmente para desarrollo local
quarkus.grpc.clients.cliente-topologia.plain-text=true

# Rabbit
mp.messaging.incoming.vehiculos-in.connector=smallrye-rabbitmq
mp.messaging.incoming.vehiculos-in.exchange.name=amq.topic
mp.messaging.incoming.vehiculos-in.routing-key=mineria.vehiculos.#

# Le damos un nombre a la cola para identificarla en la interfaz de RabbitMQ
mp.messaging.incoming.vehiculos-in.queue.name=cola.transitoria.congestiones.vehiculos

# Hacemos que sea "Dispara y Olvida" (transitoria y se borra al apagar)
mp.messaging.incoming.vehiculos-in.queue.durable=false
mp.messaging.incoming.vehiculos-in.queue.auto-delete=true

# Nuevo Cliente Notificaciones
quarkus.grpc.clients.cliente-notificaciones.host=localhost
quarkus.grpc.clients.cliente-notificaciones.port=8083
quarkus.grpc.clients.cliente-notificaciones.plain-text=true

# Cambios del Semaforo Topologia
mp.messaging.incoming.cambios-semaforos-in.connector=smallrye-rabbitmq
mp.messaging.incoming.cambios-semaforos-in.exchange.name=mina.exchange.principal
mp.messaging.incoming.cambios-semaforos-in.routing-key=semaforos.topologia.cambios

# Cola durable y persistente
mp.messaging.incoming.cambios-semaforos-in.queue.name=cola.persistente.congestiones.topologia
mp.messaging.incoming.cambios-semaforos-in.queue.durable=true

# Almacenamiento
mp.messaging.outgoing.congestiones-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.congestiones-out.exchange.name=mina.exchange.principal
mp.messaging.outgoing.congestiones-out.default-routing-key=mina.congestiones.alerta