# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

quarkus.http.port=8081
quarkus.grpc.server.port=9000
quarkus.grpc.server.use-separate-server=false

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=santyJOTO1209
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/mvts_topologia?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Hermosillo

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
