
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

# ==========================================
# CONFIGURACI\u00d3N DEL SERVIDOR RPC (Quarkus)
# ==========================================
quarkus.http.port=8081
quarkus.grpc.server.port=9000
quarkus.grpc.server.use-separate-server=false

mp.messaging.incoming.peticiones-rpc.connector=smallrye-rabbitmq
# El nombre de la cola est\u00e1tica donde escuchamos peticiones
mp.messaging.incoming.peticiones-rpc.queue.name=rpc.semaforos.topologia
# Desactivamos el auto-creado de exchange porque escuchamos directo a la cola
mp.messaging.incoming.peticiones-rpc.exchange.name=

# (Tu configuraci\u00f3n anterior del emisor de eventos)
mp.messaging.outgoing.emisor-cambios.connector=smallrye-rabbitmq
mp.messaging.outgoing.emisor-cambios.routing-key=semaforos.topologia.cambios

# 1. Apuntamos al nuevo Exchange Principal
mp.messaging.outgoing.emisor-cambios.exchange.name=mina.exchange.principal

# 2. Le decimos que es de tipo "topic"
mp.messaging.outgoing.emisor-cambios.exchange.type=topic

# 3. (Opcional pero recomendado) Darle permiso de crearlo si no existe
mp.messaging.outgoing.emisor-cambios.exchange.declare=true
mp.messaging.outgoing.emisor-cambios.exchange.durable=true
