
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

quarkus.http.port=8083
quarkus.grpc.server.use-separate-server=false

mp.messaging.outgoing.alertas-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.alertas-out.routing-key=central.notificaciones.alertas

# Nombre de tu nuevo Exchange
mp.messaging.outgoing.alertas-out.exchange.name=mina.exchange.principal
# Le decimos que es de tipo "topic" (ideal para enrutamiento con puntos)
mp.messaging.outgoing.alertas-out.exchange.type=topic
# Instruimos a Quarkus para que declare/cree el exchange si no existe
mp.messaging.outgoing.alertas-out.exchange.declare=true
# Hacemos que el exchange sobreviva a reinicios
mp.messaging.outgoing.alertas-out.exchange.durable=true